version: '2'
services:
  mlb-scores-web:
    image: "creg.tom-adams.net:5000/mlb-scores:${BUILD_NUMBER}"
  mlb-scores-nginx:
    image: "creg.tom-adams.net:5000/nginx:${BUILD_NUMBER}"
    links:
      - mlb-scores-web
    ports:
      - "80"
   
