version: '2'
services:
  mlb-scores-web:
    image: "hub.tom-adams.net:5000/tca/mlb-scores:${TAG_VERSION}"
  mlb-scores-nginx:
    image: "hub.tom-adams.net:5000/tca/nginx:${TAG_VERSION}"
    links:
      - mlb-scores-web
    ports:
      - "80"
   
